### ISSUE TITLE
Make the repository a Template repository

### ISSUE THREAD

**Issue by oliverosz** [hegyhati/Diploma_Work_Template#5]
In the Settings of the repository, check the box that says "Template repository".

This enables the repository to be used as a template when creating a new repository. See [Creating a repository from a template](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template) for more info.

Also update the instructions in the repository description accordingly.

**Comment by hegyhati** [comment]
Settings changed, description update later.
